version: "2"
services:
  sinks-databases-jvm:
    image: streampipes/sinks-databases-jvm:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:

