# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-worker
spec:
  selector:
    matchLabels:
      app: connect-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: connect-worker
    spec:
      initContainers:
        - name: init-wait-consul
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 consul 8600 && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-couchdb
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 couchdb 5984 && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-connect-worker
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 connect-master 8099 && exit 0 || sleep 3; done; exit 1"]
        - name: init-wait-kafka
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 kafka 9092 && exit 0 || sleep 3; done; exit 1"]            
      containers:
        - name: connect-worker
          image: {{ .Values.streampipes.registry }}/connect-worker:{{ .Values.streampipes.version }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: SP_CONNECT_CONTAINER_MASTER_HOST
              value: connect-master
            - name: SP_CONNECT_CONTAINER_WORKER_HOST
              value: connect-worker
            - name: SP_KAFKA_HOST
              value: kafka
          ports:
            - containerPort: 8098
