version: "2"
services:
  processors-aggregation-flink:
    image: ${SP_PE_DOCKER_REGISTRY}processors-aggregation-flink:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
#      - SP_KAFKA_HOST=
    networks:
      spnet:

