version: "2"
services:
  processors-statistics-flink:
    image: streampipes/processors-statistics-flink:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:

